"""init

Revision ID: 2f9cf8c70b78
Revises: 
Create Date: 2025-08-05 06:17:09.353229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9cf8c70b78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailings',
    sa.Column('message_ids', sa.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'RESUME', 'SENDING', 'PAUSED', 'SENT', 'FAILED', name='mailingstatus'), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=200), nullable=True),
    sa.Column('tg_first_name', sa.String(length=200), nullable=False),
    sa.Column('tg_last_name', sa.String(length=200), nullable=True),
    sa.Column('tg_bio', sa.String(length=500), nullable=True),
    sa.Column('tg_birthdate', sa.String(length=50), nullable=True),
    sa.Column('utm', sa.String(length=50), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('admin_flag', sa.Boolean(), nullable=False),
    sa.Column('registration_status', sa.Enum('UNKNOWN', name='userregistrationstatus'), server_default=sa.text("'UNKNOWN'"), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_recipients',
    sa.Column('mailing_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'RESUME', 'SENDING', 'PAUSED', 'SENT', 'FAILED', name='mailingstatus'), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mailing_id'], ['mailings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailing_id', 'recipient_id', name='uq_mailing_recipient')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing_recipients')
    op.drop_table('users')
    op.drop_table('mailings')
    # ### end Alembic commands ###
